name: Build and Push n8n-ffmpeg

on:
  workflow_call:
    inputs:
      n8n-version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      n8n-version:
        description: 'n8n version to build'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            N8N_VERSION=${{ inputs.n8n-version }}
          tags: |
            rxchi1d/n8n-ffmpeg:${{ inputs.n8n-version }}
            rxchi1d/n8n-ffmpeg:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Update README
        run: |
          echo "Last built: $(date)" >> BUILD_INFO.md
          echo "n8n version: ${{ inputs.n8n-version }}" >> BUILD_INFO.md
          
      - name: Commit build info
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add BUILD_INFO.md
          git commit -m "Built version ${{ inputs.n8n-version }}" || exit 0
          git push